"""
Module for Flutterwave payment processing integration.
This module provides functions to interact with the Flutterwave payment API,
including webhook signature validation, transaction verification, subscription
payment initialization, and transaction reference management.
The transaction reference (tx_ref) format uses a custom encoding scheme:
- Format: "so:{user_id}:{plan_code}:{timestamp}"
- The "so" prefix is a namespace identifier for SignalOps
- It enables robust webhook attribution by embedding user identity
- The timestamp provides transaction uniqueness and chronological tracking
"""


import base64
import hashlib
import hmac
import json
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from typing import Any, Dict

from app.configs.settings import settings


def is_valid_webhook_signature(raw_body: bytes, signature: str | None) -> bool:
    """Validate Flutterwave webhook HMAC signature using configured secret hash."""
    secret = (settings.flutterwave_webhook_secret_hash or "").strip()
    if not secret or not signature:
        return False

    digest = hmac.new(secret.encode("utf-8"), raw_body, hashlib.sha256).digest()
    expected = base64.b64encode(digest).decode("utf-8")
    return hmac.compare_digest(expected, signature.strip())


def verify_transaction(transaction_id: str) -> Dict[str, Any]:
    """Fetch verified transaction details from Flutterwave verify endpoint."""
    tx_id = (transaction_id or "").strip()
    if not tx_id:
        raise RuntimeError("Missing Flutterwave transaction id")

    secret_key = (settings.flutterwave_secret_key or "").strip()
    if not secret_key:
        raise RuntimeError("Flutterwave secret key is not configured")

    base_url = (settings.flutterwave_api_base_url or "https://api.flutterwave.com").rstrip("/")
    url = f"{base_url}/v3/transactions/{urllib.parse.quote(tx_id, safe='')}/verify"
    request = urllib.request.Request(
        url=url,
        headers={
            "Authorization": f"Bearer {secret_key}",
            "Accept": "application/json",
        },
        method="GET",
    )

    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            body = response.read().decode("utf-8")
    except urllib.error.HTTPError as exc:
        error_body = ""
        try:
            if exc.fp is not None:
                error_body = exc.fp.read().decode("utf-8", errors="replace")
        except Exception:
            error_body = ""
        raise RuntimeError(
            f"Flutterwave verify failed {exc.code}: {error_body or exc.reason}"
        ) from exc

    return json.loads(body)


def make_tx_ref(user_id: int, plan: str) -> str:
    """Create a tx_ref that embeds user identity for robust webhook attribution."""
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    plan_code = (plan or "").strip().lower() or "plan"
    return f"so:{int(user_id)}:{plan_code}:{timestamp}"


def parse_tx_ref_user_id(tx_ref: str | None) -> int | None:
    """Extract user_id from tx_ref format generated by make_tx_ref."""
    value = (tx_ref or "").strip()
    if not value:
        return None

    parts = value.split(":")
    if len(parts) <= 3 or parts[0] != "so":
        return None

    try:
        return int(parts[1])
    except (TypeError, ValueError):
        return None


def initialize_subscription_payment(
    *,
    tx_ref: str,
    amount: float,
    currency: str,
    customer_email: str,
    customer_name: str,
    plan_id: str,
    redirect_url: str,
    payment_options: str = "card,banktransfer,ussd",
) -> Dict[str, Any]:
    """Call Flutterwave payment initialization endpoint for recurring subscriptions."""
    secret_key = (settings.flutterwave_secret_key or "").strip()
    if not secret_key:
        raise RuntimeError("Flutterwave secret key is not configured")

    base_url = (settings.flutterwave_api_base_url or "https://api.flutterwave.com").rstrip("/")
    url = f"{base_url}/v3/payments"

    payload: Dict[str, Any] = {
        "tx_ref": tx_ref,
        "amount": round(float(amount), 2),
        "currency": currency,
        "payment_options": payment_options,
        "redirect_url": redirect_url,
        "customer": {
            "email": customer_email,
            "name": customer_name,
        },
        "customizations": {
            "title": "SignalOps Subscription",
            "description": "SignalOps plan checkout",
        },
        "meta": {
            "plan_id": plan_id,
        },
    }

    request = urllib.request.Request(
        url=url,
        headers={
            "Authorization": f"Bearer {secret_key}",
            "Content-Type": "application/json",
            "Accept": "application/json",
        },
        data=json.dumps(payload).encode("utf-8"),
        method="POST",
    )

    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            body = response.read().decode("utf-8")
    except urllib.error.HTTPError as exc:
        error_body = ""
        try:
            if exc.fp is not None:
                error_body = exc.fp.read().decode("utf-8", errors="replace")
        except Exception:
            error_body = ""
        raise RuntimeError(
            f"Flutterwave initialize failed {exc.code}: {error_body or exc.reason}"
        ) from exc

    return json.loads(body)


def checkout_link_for_plan(plan: str) -> str:
    """Return configured hosted payment link for a plan code."""
    normalized = (plan or "").strip().lower()
    if normalized == "starter":
        return (settings.flutterwave_starter_link or "").strip()
    if normalized == "pro":
        return (settings.flutterwave_pro_link or "").strip()
    return ""
